### PR TITLE
Added CNAME pointing at the vange.rs domain

### PR DESCRIPTION
**Pull request by lolmaus**
I've just paid for the fourth year of the vange.rs domain and noticed that you now have a GitHub Pages website. Let's have it use https://vange.rs .

I've configured the DNS part already, now we need to configure the repo.

The guides about using a custom domain with GitHub pages have become much more confusing than before:
https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

If I understood correctly, this PR is not strictly required. Instead, you can use project configuration UI to include the domain and the same commit will be added automatically. But I'm not sure if the UI configuration is still required if you accept this PR. 🤔

Also, you should enforce HTTPS in the project configuration (if not already).

PS Having this figured out may cause a short outage of the website. I hope it's not a big deal.

### CODE REVIEW

**Comment by lolmaus** [comment]
Related: #86.

**Comment by kvark** [comment]
Thank you!
Small update on the plan to run vange-rs in the browsers: WebGPU will become experimentally available next year, but before we can run it, we'll need to port the shaders to WGSL.

**Comment by lolmaus** [comment]
Something's not right: http://vange.rs opens GitHub's 404 page.

Please follow the guide over the link above!

**Comment by kvark** [comment]
All good now!

**Pull request merged**
