### PR TITLE
WIP: RFC for sounds support

### PR DESCRIPTION
**Pull request by NIR-Ginko**
This is an overview for libraries providing sound support before the actual development will begin.

The RFC is a Work In Progress and will be expanded as soon as I study the code and will be able to propose the changes for configuration options and API.

### CODE REVIEW

**Comment by stalkerg** [comment]
OpenAL should be the best... I didn't use it for Vangers because it has complicated API. 
Also, you should check existence for pitch effect.

**Comment by kvark** [comment]
@NIR-Ginko is this still WIP?

@stalkerg how do you feel about
> [OpenAL](https://repo.or.cz/openal-soft.git) also has a dead website at the moment and the situation looks bad

> Also, you should check existence for pitch effect.

Good point! I'll see if we can have it in Rodio/Cpal.

**Comment by stalkerg** [comment]
> OpenAL also has a dead website at the moment and the situation looks bad

Why? They have a very active repo.

**Comment by kvark** [comment]
@stalkerg it is active indeed, although not very healthy (with a single developer doing 99% of work).

There is a good value in trying to stay away from native/C dependencies in a Rust project:
  - easier build configuration: no need to Makefile/Cmake, no headache on Windows, better portability
  - benefit the community
  - sometimes, faster: can use iterators instead of slices (or even `std::vector`)

Since this is an experimental project, I'd be more motivated to implement the pitch (and other effects) support in the Cpal ecosystem, therefore.

**Comment by kvark** [comment]
@NIR-Ginko are you intending to get back to this?

**Comment by kvark** [comment]
This is sadly the way some collaborations go, and it's not the best one. Trying to plan ahead of an experimental implementation is like putting a detailed design doc for your game without writing any code: typically this work turns out to be a waste. It would be more useful if a fraction of that effort was directed at the actual code - take `rodio`, hook it up, try to load some sounds from the original game. On that note, I'm going to close the PR due to inactivity. I don't think having the doc file is useful without the original author participation at this point. Please feel free to re-open!

**Pull request closed without merging**
